### ISSUE TITLE
Redirect still acting up

### ISSUE THREAD

**Issue by KernelForbin** [ehedaya/theSloth#110]
Having issues logging in to thephish.fm/wp-admin

Is any sort of redirect still in place on your side?

**Comment by KernelForbin** [comment]
Even if attempting to do the password reset it does a weird loop and goes back to the page, won't proceed.

No way to log in to the admin panel that I can see at the time. Let me know when you can check this. We may have to switch back to plug soon due to dubtrack wiping (all playlists and rooms gone, had to recreate). If that is the case I will need to update the main redirect.

**Comment by ehedaya** [comment]
@KernelForbin sorry, I think this may have been due to the way I had the domain set up after we restored it. Can you try again now?

**Comment by KernelForbin** [comment]
Perfect. Working properly! Thanks!

Dubtrack is also back up / restored to its previous status... so we won't be moving just yet! ;)

Thanks again
