### ISSUE TITLE
Missing tracks in Stats

### ISSUE THREAD

**Issue by paug986** [ehedaya/theSloth#74]
Sometimes when a track is repeated within some amount of time, not sure if its within the same day, within the timeframe things are on the front page of stats or whatever, the track wont show up on the stats page.

For instance, PYITE>Lawn Boy was playing this morning and then played again a few hours later and did not show up again on the stats page.

**Comment by ehedaya** [comment]
This is actually by design, unfortunately, as the Plug api has no available globally unique id for each play, so I have to "make" one as a combination of the track ID and some reasonable amount of time in which to expect it to not get played again. I think it's presently 3 hours.
