### ISSUE TITLE
Replay page update

### ISSUE THREAD

**Issue by KernelForbin** [ehedaya/theSloth#80]
Two things.

1. Is it possible to have the day of the week added to the schedule? By this I mean the day it is being played, not the day of the show itself. 

2, Is it possible to remove the end time from the calendar? It doesn't seem to be working and the end time is always very vague with us anyway.

I know you use the end time for the status of the !replay command, so that can still be there, but it doesn't need to be displayed on the schedule.

So like:

Mon. 2015-07-27 2:00 pm | Replay of 2015-07-24 - Shoreline Amphitheatre Mountain View CA USA

**Comment by KernelForbin** [comment]
As I posted this I realized the "-04:00" may be referring to the Timezone? Is that at all possible/accurate? It isn't the same format as the 2pm. And it isn't the correct timezone anyway. If that could be removed then cool.  Thanks!

**Comment by ehedaya** [comment]
It does, yes.  I can make it easier to read though.

**Comment by ehedaya** [comment]
Actually would you mind writing exactly what you would ideally want it to say? Eg " The next replay will be Friday, July 24, 2015 at 4:00 PM"

**Comment by KernelForbin** [comment]
I mean on the actual schedule page

http://stats.thephish.fm/replays.html

The first column, currently reads:

"2015-07-27 2:00 pm -04:00"

instead could it read:

"Monday 2015-07-27 2:00 pm ET"
