### ISSUE TITLE
Remove Non-Phish Songs from Phish show pages

### ISSUE THREAD

**Issue by paug986** [ehedaya/theSloth#89]
It would be nice to be able to remove tracks that have dates the same as a Phish show, but aren't Phish tracks. For instance the Umphreys track listed here.

https://stats.thephish.fm/2015-12-31_madison-square-garden-new-york-ny-usa

The delete button doesn't seem to work.

**Comment by ehedaya** [comment]
This can be done by editing the track and clearing out the showdate field.   I did this for the track you listed and it seems to have worked

https://stats.thephish.fm/play_56bd03bed0f13a69027f409c&nocache=1
