### ISSUE TITLE
Some sort of TiPH functionality

### ISSUE THREAD

**Issue by KernelForbin** [ehedaya/theSloth#93]
tiph dedicated page might be best/cleanest as some dates may have quite a few matches and it may clutter up the home page. With a dedicated page we wouldn't have to worry about saving space.

Each date could link to the show page in stats

!tiph could return http://thephish.fm/tiph

and I will set up the fwd to whatever the page ends up being

**Comment by ehedaya** [comment]
http://stats.thephish.fm/XXXX-05-04
