### ISSUE TITLE
Entering the Date for tracks in stats messed up

### ISSUE THREAD

**Issue by paug986** [ehedaya/theSloth#94]
The edit feature on stats in the date section to put in the date for the show looks all messed up.

It no longer is "2003-07-26 VENUE" like before. It looks like 07/26/2003 but the MM/DD/YYYY is on top of it and entering the date doesn't seem to work the same way.

I can provide a screen shot if necessary.

**Comment by ehedaya** [comment]
@paug986 I think this is fixed, I just never closed the issue.  Re-open if this is not the case.
