### ISSUE TITLE
!setlist and !who commands to pull from stats not room

### ISSUE THREAD

**Issue by paug986** [ehedaya/theSloth#99]
Can the !setlist and !who commands pull data from the tags in stats and not the title of the play in the dub room?

**Comment by ehedaya** [comment]
@paug986 I think I have done this, please make sure you have v0.7.19 of the extension and give it a go!

**Comment by paug986** [comment]
Looks like its working now. Not sure if you changed anything or reverted it back.

**Comment by paug986** [comment]
I take that back. Trying to add a date to some other tracks its not going through. Not sure why it worked on that one Martian Monster track, but its not working again for any of the tracks from this day https://stats.thephish.fm/?date=2017-01-20
